version: '3'

services:
  # MySQL Service
  mysql_server:
    image: mysql:latest
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dassco-au
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Dockerfile Service
  web:
    build:
      dockerfile: Dockerfile
    container_name: nhmaspeciesweb
    ports:
      - "3000:3000"
    depends_on:
      - mysql_server
    env_file:
      - .env.local

volumes:
  mysql_data: